### ISSUE TITLE
This is cool. Got a question.

### ISSUE THREAD

**Issue by spencerthayer** [apg/heroku-tor-buildpack#3]
I'm interested in integrating TOR with this project of mine called [AnonBoard](https://github.com/spencerthayer/AnonBoard). The basic goal behind this is a totally anonymous board with integrated javascript AES encryption for posts. Since it's javascript the key is never stored. I want anyone to be able to use this and I'm trying to figure out how to integrate AnonBoard with TOR and the deploy to Heroku button.

Any tips?

**Comment by apg** [comment]
First, I think I should definitely point out that this buildpack hasn't been updated to default to the latest TOR, so there's that. That's probably a trivial thing to do though; have it download the latest release instead, and done. It also doesn't try to prove the integrity of the release. I had wanted to add this a while back but never got around to making it work exactly.

Second, keep in mind that Heroku, by default, if you use a dyno type named web, will route traffic to your dyno that escapes the TOR setup. To avoid that, you'll need to avoid the use of the `web` dyno type and pick `hiddenweb` or something else.

Third, a Heroku button deploy would have a bootstrapping problem. This is because the TOR buildpack, if not present in the environment, will start TOR without a *known* private key and .onion name, in which case it will *create* one but you'll have no way of knowing what it is... 

A button compatible way, however, might be to use the `compile` step, during the build process, to generate the private key and .onion, cache them to `CACHE_DIR`, and install them at build time. This would require modifications (deletions, really) to the `hide` script, which currently expects env vars to generate the necessary files.

In order to get the .onion that's being used, then, you'd have to do `heroku run cat /app/hidden_service/hostname`, which isn't a big deal, really... Bonus points if you supported both methods!

I'm not sure when, if ever, I'll have time to update this buildpack to do all that. If you're interested, I'm happy to accept a PR, but it might be the case that at that point, you just fork and do what you need. I'm happy to point people to your fork, too.

**Comment by spencerthayer** [comment]
Thanks for the info. This is certainly something I am going to attempt to get working.

**Comment by cbeams** [comment]
Did anything ever become of this? In particular, I'm interested in getting @apg's suggestions about `CACHE_DIR` properly supported in the buildpack. Right now, my app takes ages to deploy as it's necessary to download and compile Tor every time.

I don't care so much about automating the process of .onion and private key generation (though that would be nice)—I care much more about the turnaround time for each and every deploy after first-time setup.

Note that I'm using @hernanex3's fork of this repo, because it was the most up-to-date and his changes made sense to me. I've looked around the other forks, and I haven't seen anyone implementing caching of the built Tor artifacts. It would be a huge timesaver if someone did this! Thanks.

**Comment by herhernan** [comment]
@cbeams as you wish sir... now tor compilation is cached. You only have to change now the run command in your `procfile` and you are ready to go.

**Comment by cbeams** [comment]
Beautiful, @hernanex3—caching now works like a charm. Thank you so much!
